### ISSUE TITLE
Display Bitmaps on Gizmo with CPBluefruit

### ISSUE THREAD

**Issue by djecken** [adafruit/Adafruit_CircuitPython_ST7789#10]
Trying to adapt the bitmap demo code from the circuit python display learn guide to run on the TFT gizmo using circuit playground bluefruit.

https://learn.adafruit.com/circuitpython-display-support-using-displayio/display-a-bitmap

Code runs fine but the display only shows black lit screen.

**Comment by makermelissa** [comment]
What code do you have so far?

**Comment by djecken** [comment]
`"""
This test will initialize the display using displayio and draw a solid green
background, a smaller purple rectangle, and some yellow text.
"""
import board
import busio
import displayio
import terminalio
from adafruit_display_text import label
from adafruit_st7789 import ST7789
import adafruit_imageload

# Release any resources currently in use for the displays
displayio.release_displays()

spi = busio.SPI(board.SCL, MOSI=board.SDA)
tft_cs = board.RX
tft_dc = board.TX
tft_backlight = board.A3

display_bus = displayio.FourWire(spi, command=tft_dc, chip_select=tft_cs)

display = ST7789(display_bus, width=240, height=240, rowstart=80,
                 backlight_pin=tft_backlight, rotation=180)

# Open the file
with open("/purple.bmp", "rb") as bitmap_file:
 
    # Setup the file as the bitmap data source
    bitmap = displayio.OnDiskBitmap(bitmap_file)
 
    # Create a TileGrid to hold the bitmap
    tile_grid = displayio.TileGrid(bitmap, pixel_shader=displayio.ColorConverter())
 
    # Create a Group to hold the TileGrid
    group = displayio.Group()
 
    # Add the TileGrid to the Group
    group.append(tile_grid)
 
    # Add the Group to the Display
    display.show(group)

while True:
    pass
`

**Comment by makermelissa** [comment]
Thanks, I don't seem to be able to get it working either. I'm wondering if it may be an issue with OnDiskBitmap and the fact that we're using different pins for SPI than normal with this. Also, I'm not sure if it was an artifact from a previous test, but adafruit_imageload isn't required for this.

**Comment by makermelissa** [comment]
I'll have to try hooking up a saleae later to see if we're getting data on the expected pins.

**Comment by djecken** [comment]
sounds good, thanks! I hope to be able to use the slideshow library with the Gizmo TFT at some point as well.

**Comment by FoamyGuy** [comment]
@djecken @makermelissa I think this is covered now by the [gizmo library](https://github.com/adafruit/Adafruit_CircuitPython_Gizmo) right? The examples on this learn guide page: https://learn.adafruit.com/circuitpython-display-support-using-displayio/display-a-bitmap 

can be done with only slight modification using the gizmo library: 
```
from adafruit_gizmo import tft_gizmo

display = tft_gizmo.TFT_Gizmo()
```

Though the included `purple.bmp` is bigger than the gizmo screen. I used a 240 x 240 blinka bmp file was able to show it on the screen like this.

**Comment by kattni** [comment]
@FoamyGuy Can you try testing the TFT Gizmo with the Adafruit CircuitPython Slideshow library as well?

**Comment by FoamyGuy** [comment]
@kattni Yep, I can test that out later tonight.

**Comment by FoamyGuy** [comment]
@kattni `slideshow_tft_gizmo.py` from inside the examples folder of the slideshow repo is working successfully on a CPB + TFT Gizmo

**Comment by kattni** [comment]
@djecken Looks like you should be good to go! 

Closing.
