### ISSUE TITLE
This driver seemes not working with ST7789 with CS pin to ground

### ISSUE THREAD

**Issue by rxing365** [adafruit/Adafruit_CircuitPython_ST7789#28]
Hello,

I have a ST7789 screen, like the one in the link below, which has its CS pin connected directly to GND. 
I can't initialize the screen, it keeps showing a black screen. How can I fix it?

Thank you，
Xing

https://nl.aliexpress.com/item/1005003381703710.html?spm=a2g0o.productlist.0.0.45f96ee1jJNqHn&algo_pvid=4914bab9-a37d-438a-a21e-121a30a94272&algo_exp_id=4914bab9-a37d-438a-a21e-121a30a94272-0&pdp_ext_f=%7B%22sku_id%22%3A%2212000025518790453%22%7D&pdp_pi=-1%3B2.93%3B-1%3B167%40salePrice%3BUSD%3Bsearch-mainSearch

**Comment by ladyada** [comment]
it cannot work, CS is required for this library!

**Comment by rxing365** [comment]
I see. I soldered my own CS tap and connected it up to the GPIO and now it's working.
