### ISSUE TITLE
DisplayIO missing from library

### ISSUE THREAD

**Issue by djecken** [adafruit/Adafruit_CircuitPython_ST7789#9]
Testing TFT Gizmo example with Circuit Playground Express running Circuit Python V5 alpha 4. I have the following libraries installed from circuit python 5 bundle: 

adafruit_bus_device
adafruit_display_shapes
adafruit_display_text
adafruit_st7789.mpy

`Traceback (most recent call last):
  File "code.py", line 7, in <module>
ImportError: no module named 'displayio'`

**Comment by jerryneedell** [comment]
Are you using the circuit_playground_express_displayio build?
https://adafruit-circuit-python.s3.amazonaws.com/index.html?prefix=bin/circuitplayground_express_displayio/en_US/

**Comment by makermelissa** [comment]
We should add this to the downloads page so it can be linked to in the guide.

**Comment by makermelissa** [comment]
I'll update the guide with Jerry's link for now though.

**Comment by makermelissa** [comment]
Fixed in TFT Gizmo guide.

**Comment by djecken** [comment]
Thanks! Testing cpx now with latest UF2 displayio build and getting new error. Display loads graphics for a brief second before crashing and going to REPL.

`code.py output:
Traceback (most recent call last):
  File "code.py", line 39, in <module>
MemoryError: memory allocation failed, allocating 5600 bytes`

**Comment by makermelissa** [comment]
Yeah, if you look at the TFT gizmo guide at the top, there's already a warning about that. It has enough memory to run drawing or maybe just label, but not both.

**Comment by djecken** [comment]
ah OK gotcha, will switch to a CP bluefruit :-)

**Comment by djecken** [comment]
works good on the circuit playground bluefruit!
